name: Node.js CI

# Controls when the workflow will run

# Make sure all permissions are granted:
# github repo -> Settings -> Actions -> General -> Workflow permissions -> Read and write permissions

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - run: npm ci
      - run: npm run build --if-present

      # The script for testing the application should be the same as in the 'package.json' file
      - name: Run tests
        run: npm run test:ci

      - name: Build
        run: npm run build
